bit-bots/bitbots_misc

bitbots_teleop/scripts/teleop_keyboard.py

small fix in keyboard script to make it stable against partial joint state messages

Teleop small fix

---

bitbots_bringup/scripts/motor_goals_viz_helper.py

Fixed outdated version of motor goals viz script. Also added support via arguments for bypassing HCM

Feature motor viz script

---

bitbots_bringup/launch/motion.launch

The launchfile got the new walking argument which defines whether the walking is started or not. Especially useful for the simulations with fake_walk.

added launchfile argument for walking

---

bitbots_bringup/launch/simulator.launch

An argument to state which camera should be used in simulation is added.

added basler parameter

---

bitbots_bringup/scripts/keep_stable_in_sim.py

keeps the ball on the floor by resetting the z-value in a fixed rate

keeping the ball on the floor

---

bitbots_bringup/launch/highlevel.launch
bitbots_bringup/launch/simulator.launch
bitbots_bringup/launch/teamplayer.launch
bitbots_bringup/launch/tools.launch

Separate launch file for tools

---

bitbots_bringup/launch/motion.launch

small fix to have the button module not running in simulation which produces errors. It is not needed there in my opinion anyway

removed button from motion launch when simulating

---

.gitignore
bitbots_docs/cmake/enable_bitbots_docs.cmake.in

While writing a bit more documentation I noticed a few bugs. They are described in the commit messages and are hereby fixed.
For proper use of the new documentation system this should be merged as soon as possible.

Important fixes for bitbots_docs

---

bitbots_bringup/src/bitbots_bringup/game_settings.py

* Remove ROS runtime dependency
* explicitly use unsafe yaml loader

Game settings fixes

---

bitbots_ceiling_cam/CMakeLists.txt
bitbots_ceiling_cam/README
bitbots_ceiling_cam/config/april_tag_settings.yaml
bitbots_ceiling_cam/config/april_tags.yaml
bitbots_ceiling_cam/config/camera_calibration_ceiling_cam.yaml
bitbots_ceiling_cam/config/camera_settings_ceiling_cam.yaml
bitbots_ceiling_cam/launch/ceiling_cam.launch
bitbots_ceiling_cam/package.xml
bitbots_ceiling_cam/setup.py

this introduces a new package which provides launch and config files for the ceiling camera. I tested it and it works. It also should not interfere with the robot software in any way

package ceiling cam

---

bitbots_bringup/scripts/game_settings.py
bitbots_bringup/src/bitbots_bringup/game_settings.py

for better compatibility with peoples environments, all dependencies
from game_settings to ROS were removed

game_settings: remove dependencies to ROS

---

bitbots_bringup/scripts/motor_goals_viz_helper.py

necessary for visualizing dynup

viz_helper: add option for dynup

---

bitbots_bringup/launch/highlevel.launch
bitbots_bringup/launch/motion.launch
bitbots_bringup/launch/teamplayer.launch

otherwise, the odometry fuser would not be started in motion and therefore not in teamplayer

Fix launch files 

---

bitbots_bringup/launch/load_robot_description.launch
bitbots_bringup/launch/motion.launch
bitbots_bringup/launch/simulator.launch
bitbots_bringup/launch/simulator_teamplayer.launch
bitbots_bringup/package.xml

fix odom launch + remove respawn

---

bitbots_bringup/package.xml
bitbots_bringup/scripts/game_settings.py
bitbots_bringup/scripts/keep_stable_in_sim.py
bitbots_bringup/scripts/publish_ball_relative.py
bitbots_bringup/scripts/set_motor_position.py
bitbots_bringup/src/bitbots_bringup/game_settings.py
bitbots_bringup/src/bitbots_bringup/goals_to_joint_states.py
bitbots_live_tool_rqt/scripts/live_tool_udp.py
bitbots_live_tool_rqt/scripts/test_node.py
bitbots_live_tool_rqt/scripts/walking_tool.py
bitbots_teleop/package.xml
bitbots_teleop/src/bitbots_teleop/joy_node.py

This pull request updates all shebangs to python3 as we will discuss in our weekly.

Update shebangs to python3

---

Jenkinsfile
bitbots_bringup/CMakeLists.txt
bitbots_bringup/package.xml

Adds a Jenkinsfile for automatic build using the bitbots_jenkins_library.

Add jenkinsfile

---

bitbots_pixel_visualizer/cfg/PixelVisualizer.cfg

change shebang and or package.xml to work with python3
- ~~[ ] Update package version~~
- ~~[ ] Run linters~~
- ~~[ ] Write documentation~~
- ~~[x] Test on your machine~~

python3 compatability

---

bitbots_teleop/src/bitbots_teleop/joy_node.py

Use the numbers on the controller to set head modes for the head behavior. This is useful for behavior testing.

Use controller numbers for head modes

---

bitbots_bringup/launch/load_robot_description.launch
bitbots_bringup/package.xml

Changes URDF part for new onshape urdf
only merge with https://github.com/bit-bots/wolfgang_robot/pull/36

bringup: changed urdf file path

---

bitbots_bringup/launch/motion.launch
bitbots_bringup/package.xml

This pull request introduces a launch file for the dynamic kick.

use launch file for dynamic kick

---

bitbots_bringup/package.xml
bitbots_bringup/scripts/check_robot.py

should solve https://github.com/bit-bots/bitbots_motion/issues/110

bringup: improve check robot script

---

bitbots_bringup/package.xml
bitbots_bringup/scripts/extract_profiler.py
bitbots_bringup/scripts/rosbag_to_pandas.py

scripts for walking paper experiment
rosbag to pandas dataframe...

bringup: utility scripts for evaluation

---

system_monitor/config/config.yaml
system_monitor/msg/Workload.msg
system_monitor/package.xml
system_monitor/src/system_monitor/cpus.py
system_monitor/src/system_monitor/monitor.py

Adds publishing of diagnostic messages to the system monitor so that they are displayed in rqt diagnostic view.
partly solves https://github.com/bit-bots/bitbots_misc/issues/16

system monitor: add diagnostic messages

---

bitbots_bringup/launch/highlevel.launch
bitbots_bringup/launch/simulator_teamplayer.launch
bitbots_bringup/package.xml

Modifies launch files so that they work with new simulator.

fix launch files for simulation

---

bitbots_bringup/launch/simulator.launch
bitbots_bringup/launch/simulator_teamplayer.launch
bitbots_time_constraint/config/constraints.yaml

renames image message in order to be compatible with changes in bitbots_vision

renamed image_raw to camera/image_proc where necessary

---

bitbots_bringup/config/game_settings.yaml
bitbots_bringup/config/to_be_set_game_settings.yaml
bitbots_bringup/package.xml

The setting role_position was added to the game setting config files because this setting is needed in the behavior now.
#74

Feature: new game setting

---

bitbots_bringup/package.xml
bitbots_bringup/scripts/rosbag_to_pandas.py

Adds a couple of convenience features to the script:
- printing how far the process is
- saving user input, so that multiple bags can be processed easier
- optionally removing time offset
- optionally creating seperate coloumns in the dataframe for array data
- option to provide an output folder
~- [ ] Test on the robot~

add some more functionallity to rosbag extraction script

---

bitbots_bringup/scripts/rosbag_to_pandas.py

Tiny PR to fix some prints in the pandas script

Prints in pandas script

---

bitbots_convenience_frames/src/convenience_frames.cpp

When the clock is manually published at a lower rate than 100Hz, the main loop in `convenience_frames` is run twice. Then, the transforms are published twice. ROS Noetic complains about that by filling the terminal with error messages.

convenience frames: fix duplicate publishing in simulation

---

bitbots_bringup/launch/motion.launch
bitbots_bringup/package.xml
bitbots_bringup/scripts/motor_goals_viz_helper.py

fixes for https://github.com/bit-bots/bitbots_motion/pull/172
only merge together!!!!

small fix for new dynup version

---

bitbots_teleop/config/controller.yaml
bitbots_teleop/launch/robot_teleop.launch
bitbots_teleop/src/bitbots_teleop/joy_node.py

Add config for multiple controllers

---

bitbots_bringup/launch/highlevel.launch
system_monitor/launch/viz.launch
system_monitor/src/system_monitor/monitor.py

namespaces in system monitor and launch file fix

---

bitbots_bringup/scripts/tf_monitor.py

When using the tf monitor do display a chain, only show the tf broadcasters that are part of this chain.

tf monitor: only show participating nodes in chain mode

---

bitbots_bringup/launch/simulator_teamplayer.launch

Launch localization on default in simulation
~- [ ] Run `catkin build`~
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on the robot~

Launch localization on default in simulation

---

bitbots_bringup/launch/highlevel.launch

remove motion param from highlevel launch

---

bitbots_convenience_frames/CMakeLists.txt
bitbots_convenience_frames/include/bitbots_convenience_frames/convenience_frames.h
bitbots_convenience_frames/src/convenience_frames.cpp

Necessary for https://github.com/bit-bots/bitbots_motion/pull/223

conv frames: use new support msg

---

bitbots_bringup/launch/highlevel.launch

Add ballfilter to highlevel

---

bitbots_convenience_frames/include/bitbots_convenience_frames/convenience_frames.h
bitbots_convenience_frames/launch/convenience_frames.launch
bitbots_convenience_frames/src/convenience_frames.cpp

Removes ball approach frame
https://github.com/bit-bots/bitbots_behavior/pull/141

Remove ball approach frame

---

bitbots_bringup/launch/simulator.launch

Add headless to simulator.launch

---

bitbots_convenience_frames/CMakeLists.txt
bitbots_convenience_frames/src/convenience_frames.cpp

Same as bit-bots/bitbots_motion#256.

use -Wall in convenience frames

---

bitbots_bringup/scripts/dummy_imu.py
bitbots_bringup/scripts/keep_stable_in_sim.py
bitbots_bringup/scripts/motor_goals_viz_helper.py
bitbots_live_tool_rqt/scripts/test_node.py
bitbots_ros_patches/CMakeLists.txt
bitbots_ros_patches/package.xml
bitbots_ros_patches/setup.py
bitbots_ros_patches/src/bitbots_ros_patches/rate.py
bitbots_time_constraint/src/bitbots_time_constraint/check_constraints.py
system_monitor/config/config.yaml
system_monitor/src/system_monitor/monitor.py

ros patches

---

bitbots_teleop/scripts/teleop_keyboard.py

Adds more different kicks in keyboard teleop

teleop: more kicks

---

bitbots_bringup/launch/visualization.launch

For https://github.com/bit-bots/humanoid_league_misc/pull/89

add team comm marker to viz launch

---

bitbots_live_tool_rqt/scripts/status_msg.py

Update status_msg to new strategy
bit-bots/humanoid_league_msgs/pull/29
~- [ ] Run `catkin build`~
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on your machine~
~- [ ] Test on the robot~

Update status_msg to new strategy

---

system_monitor/config/config.yaml
system_monitor/src/system_monitor/monitor.py

fix sleep of system monitor

---

bitbots_teleop/scripts/teleop_keyboard.py

fix teleop for walk changes

---

bitbots_teleop/scripts/teleop_keyboard.py

Some smaller improvements for teleop script. 
- Corrects walkready
- Corrects reset service call
- Clearer terminal output

Teleop improvements

---

bitbots_teleop/bitbots_teleop/joy_node.py
bitbots_teleop/config/controller.yaml
bitbots_teleop/launch/robot_teleop.launch

Fix joy teleop ros2

---

bitbots_utils/launch/base.launch

reduce unnecessary spam

---

bitbots_bringup/launch/motion.launch

The kick is now ready for ROS2, this includes it into the motion launch file.

Include kick in motion launch file

---

bitbots_utils/scripts/motor_goals_viz_helper.py

This correctly parses arbitrary ros arguments by ignoring them.

Fixes for motor_goals_viz_helper

---

bitbots_bringup/launch/highlevel.launch
bitbots_bringup/launch/visualization.launch
bitbots_utils/config/game_settings.yaml
bitbots_utils/launch/base.launch

Launch file fixes for bringup and utils.

Some launch file fixes

---

bitbots_utils/scripts/speak_ip.py

utils: add speak ip script

---

bitbots_bringup/launch/highlevel.launch
bitbots_bringup/launch/visualization.launch

Fix launch files

---

bitbots_utils/bitbots_utils/game_settings.py
bitbots_utils/config/game_settings.yaml
bitbots_utils/config/global_parameters.yaml
bitbots_utils/scripts/game_settings.py

1. replace `ros_parameters` with `ros__parameters`
2. add example parameters so you are not forced to execute the script
3. add goal_width to global parameters
4. fix import

Fixes for game settings script

---

bitbots_basler_camera/launch/basler_camera.launch

composable_node does not support it, only node_container does.

Remove wrongly added taskset

---

bitbots_extrinsic_calibration/CMakeLists.txt
bitbots_extrinsic_calibration/config/amy.yaml
bitbots_extrinsic_calibration/config/default.yaml
bitbots_extrinsic_calibration/config/donna.yaml
bitbots_extrinsic_calibration/config/jack.yaml
bitbots_extrinsic_calibration/config/melody.yaml
bitbots_extrinsic_calibration/config/rory.yaml
bitbots_extrinsic_calibration/include/extrinsic_calibration/extrinsic_calibration.h
bitbots_extrinsic_calibration/launch/calibration.launch
bitbots_extrinsic_calibration/package.xml
bitbots_extrinsic_calibration/src/extrinsic_calibration.cpp
bitbots_utils/launch/base.launch

- Add calibration tf publisher
- Add node to base launch

Extrinsic calibration

---

bitbots_utils/bitbots_utils/utils.py

Add function to set parameters of another node

---

bitbots_utils/bitbots_utils/utils.py

The method was removed upstream (https://github.com/ros2/ros2cli/pull/716) but we use it here https://github.com/bit-bots/bitbots_motion/pull/363

utils: add parse parameter method that was removed upstream

---

bitbots_teleop/bitbots_teleop/joy_node.py
bitbots_teleop/config/controller.yaml

- Add full stop via button to teleop
- Some cleanup

Add full stop to teleop

---

bitbots_teleop/scripts/teleop_keyboard.py

Fixes walkick in teleop

---

bitbots_bringup/launch/highlevel.launch
bitbots_bringup/launch/visualization.launch
bitbots_ipm/CMakeLists.txt
bitbots_ipm/config/ipm.rviz
bitbots_ipm/config/soccer_ipm.yaml
bitbots_ipm/launch/ipm.launch
bitbots_ipm/package.xml
bitbots_ipm/setup.py

- Create a package that holds all Bit-Bots specific configs and launch files for the inverse perspective mapping. 
- Add an ipm launch file
- Port configs

Create `bitbots_ipm` package

---

bitbots_bringup/launch/motion.launch

- Fix sim param for animation server launch

Pass sim param to animation server

---

bitbots_utils/bitbots_utils/utils.py

- Fix param dict creation in utils. (For more than 2 nesting levels)
- Optimize code performace

Fix parameter dict creation

---

bitbots_utils/scripts/motor_goals_viz_helper.py

Speed was wrong because the update_time variable was set at the wrong place.

Fix motor goals viz helper

---

bitbots_basler_camera/config/camera_calibration_jack.yaml
bitbots_basler_camera/launch/basler_camera.launch
bitbots_extrinsic_calibration/config/amy.yaml
bitbots_extrinsic_calibration/config/default.yaml
bitbots_extrinsic_calibration/config/donna.yaml
bitbots_extrinsic_calibration/config/jack.yaml
bitbots_extrinsic_calibration/config/melody.yaml
bitbots_extrinsic_calibration/config/rory.yaml

- Use image_proc rectification as our wide angle lens is quite distorted.

Use rectified image

---

bitbots_bringup/launch/highlevel.launch
bitbots_utils/launch/README.md
bitbots_utils/launch/audio.launch
bitbots_utils/launch/tools.launch
bitbots_utils/package.xml

Add audio launch file

---

bitbots_bringup/launch/highlevel.launch

Add missing dollar sign

---

bitbots_basler_camera/package.xml
bitbots_bringup/package.xml
bitbots_ceiling_cam/package.xml
bitbots_convenience_frames/package.xml
bitbots_extrinsic_calibration/package.xml
bitbots_ipm/package.xml
bitbots_teleop/package.xml
bitbots_utils/package.xml
system_monitor/package.xml

to allow for new features like conditional depends accoring to rep [0149].
We use this to differentiate between dependencies required on robots and in
the simulation.
[149]: https://www.ros.org/reps/rep-0149.html

fix(package.xml): upgrade to version 3

---

bitbots_tf_listener/CMakeLists.txt
bitbots_tf_listener/README.md
bitbots_tf_listener/bitbots_tf_listener/__init__.py
bitbots_tf_listener/package.xml
bitbots_tf_listener/setup.py
bitbots_tf_listener/src/bitbots_tf_listener.cpp

This TF Listener improves performance while listening to TF messages.

Add drop-in replacement for TF Listener

---

bitbots_bringup/launch/highlevel.launch
bitbots_bringup/launch/simulator_teamplayer.launch
bitbots_bringup/launch/teamplayer.launch

Alllowing launching of different behavior dsd file

feat(behavior): add behavior_dsd_file arguments to launch files

---

bitbots_bringup/launch/rosbag_record.launch.py

Small refactor of `rosbag_record.launch.py`

Small refactor of `rosbag_record.launch.py`
