- bitbots_bringup/launch/simulator.launch
We should start the odom to map node always in the simulation.
> always starting odom to map

- bitbots_bringup/launch/motion.launch
- bitbots_bringup/launch/motion_standalone.launch
This PR adds a `torqueless_mode` launch parameter for the motion launch.
Closes bit-bots/bitbots_motion#74.
> bitbots_bringup: adds torqueless_mode launch param for motion

- .gitignore
- bitbots_bringup/launch/highlevel.launch
- bitbots_bringup/launch/remote_vision.launch
- bitbots_bringup/launch/teamplayer.launch
- bitbots_bringup/package.xml
- bitbots_bringup/scripts/launch_on_remote.sh
This adds the possibility to launch launch files on another machine out of a launch file.
It includes also a demo implementation using the vision launch on the jetson.
> Add a remote launch script and a vision reference implementation

- bitbots_bringup/package.xml
- bitbots_bringup/scripts/set_volume.sh
set_volume should always return with exit code 0. Therefore on the robot without a speaker, the node does not show up in red but finishes cleanly instead.
> set_volume: always exit with exit code 0

- Jenkinsfile
- bitbots_bringup/launch/load_robot_description.launch
- bitbots_convenience_frames/CMakeLists.txt
- bitbots_convenience_frames/include/bitbots_convenience_frames/convenience_frames.h
- bitbots_convenience_frames/launch/convenience_frames.launch
- bitbots_convenience_frames/package.xml
- bitbots_convenience_frames/src/convenience_frames.cpp
This is supposed to publish additional frames which are helpful for other nodes. First frame is the "apporach_frame" which is between both feed but in x axis at the front of the robot. It can be used to approach a ball more easily
Also solves
https://github.com/bit-bots/bitbots_misc/issues/48
> add new package convenience frames

- bitbots_bringup/launch/load_robot_description.launch
- bitbots_bringup/package.xml
Small fix to correctly set use_sim_time parameter, so that simulation actually uses simulation clock and not wall clock
> fix setting sim time active

- bitbots_bringup/launch/motion.launch
- bitbots_bringup/launch/motion_viz.launch
- bitbots_bringup/package.xml
Modified the motion launchscript to execute dynup.launch instead of directly starting the node; added an rviz motion launchscript
> Fix for loading dynup params correctly

- bitbots_bringup/launch/motion.launch
- bitbots_bringup/package.xml
just a small move of launch file.
Since the speaker node is basically the interface for the audio hardware, it makes more sense to have it in the ros control launch.
Needs to be merged together with 
https://github.com/bit-bots/bitbots_lowlevel/pull/57
> bringup: move speaker to ros control launch

- bitbots_teleop/package.xml
- bitbots_teleop/scripts/teleop_keyboard.py
Fixes the interface of the teleop keyboard script. Makes it more clear how to move the head.
> teleop: made head movement clear

- bitbots_bringup/launch/load_robot_description.launch
Only use one odom while using fake walking in gazebo. Otherwise, the robot jumps in odd positions.
> Only launch gazebo fakewalk odom

- bitbots_convenience_frames/package.xml
- bitbots_convenience_frames/src/convenience_frames.cpp
This adds a new frame (`ball_approach_frame`) that is located 10cm in front of the `approach_frame`. It will be used in the behavior to approach the ball but avoid running into it.
> convenience frames: add ball_approach_frame

- bitbots_bringup/launch/simulator.launch
I started webots with ``roslaunch bitbots_bringup simulator.launch`` and the robot did not move. It works after removing this line.
> remove unnecessary remap of imu

- bitbots_bringup/scripts/tf_monitor.py
In tf2, there is no tf monitor and it cannot be added to tf2 because no further changes are done for ros 1.
I therefore moved the monitor script here and reimplemented it in python, since it is extremely useful when debugging transforms.
> Add a tf_monitor script

- bitbots_bringup/launch/visualization.launch
In #96, I confused `default` and `value` in `visualization.launch`, therefore the arguments could not be set on the command line.
> Fix arguments in visualization.launch

- bitbots_bringup/scripts/tf_monitor.py
Sets a fixed number of decimal places to be printed with trailing zeroes.
This is easier to read in the terminal.
> tf_monitor: fixed number of decimal places for easier reading

- bitbots_teleop/scripts/teleop_keyboard.py
Adds kick, walkready and reset to teleop_keyboard
Restyled the info message so that it better fits into terminal
> teleop: add kick, walkready and reset

- Jenkinsfile
- bitbots_bringup/.rdmanifest
- bitbots_ceiling_cam/.rdmanifest
- bitbots_live_tool_rqt/.rdmanifest
- bitbots_time_constraint/.rdmanifest
- system_monitor/.rdmanifest
As the title says, this PR reformats Jenkinsfile to the new format so that our CI passes again.
It also adds *.rdmanifest* files so that the packages can be installable through rosdep via the source package manager.
This PR only includes the packages *bitbots_bringup*, *bitbots_ceiling_cam*, *bitbtos_live_tool_rqt*, *bitbots_time_constraint* and *system_monitor* because only those packages have all their dependencies already installable in CI.
> Fix CI and make packages resolvable via source rosdep

- bitbots_bringup/launch/visualization.launch
- bitbots_bringup/scripts/dummy_imu.py
Publishing the IMU is now required for the odometry fuser, this adds a dummy imu publisher to the visualization (the only case where odom is needed but no imu is published).
https://github.com/bit-bots/bitbots_motion/pull/233
> Add dummy imu publisher script for visualization

- bitbots_bringup/launch/highlevel.launch
- bitbots_bringup/launch/simulator_teamplayer.launch
This extends #112  and makes launching the ball filter optional for debugging
> Make ball filter optional for debugging

- bitbots_bringup/config/multirobot.rviz
- bitbots_bringup/launch/rviz_multirobot.launch
This adds an rviz file and a launch file to bitbots_bringup which can be used to display multiple robot positions, their move base goals, and move base paths. It looks like this:
Closes #115.
> Add visualization for multiple robots

- bitbots_bringup/scripts/motor_goals_viz_helper.py
Small fix for torque control, only used in visualization, not in production system.
Torque control is now simply ignored in this script.
Required so that the script is not broken with bit-bots/bitbots_motion#298.
> Small fix for torque control

- bitbots_bringup/launch/motion.launch
- bitbots_bringup/launch/motion_standalone.launch
Did not match name in bitbots_ros_control
> bringup: fix wrong launch arg

- bitbots_bringup/package.xml
Temporary remove the deps in the bringup to enable building with broken sup components to use things like the basler launch file.
> Comment out bringup deps

- bitbots_teleop/package.xml
Signed-off-by: Kenji Brameld <kenjibrameld@gmail.com>
Fix package.xml so rosdep works.
Here is the [tf_transformations key in rosdistro/rolling/distribution.yaml](https://github.com/ros/rosdistro/blob/809dffb01f9c3eacf663f3d212492341630943a2/rolling/distribution.yaml#L4768)
> fix dependency names

- bitbots_utils/CMakeLists.txt
To keep them executable when `--symlink-install` is not used.
> Use source permissions for script install

- bitbots_utils/bitbots_utils/utils.py
Add `get_parameters_from_other_node`.
Used to receive parameters from other running nodes.
bit-bots/bitbots_behavior/pull/267
> Add get_parameters_from_other_node

- bitbots_bringup/launch/highlevel.launch
- bitbots_bringup/package.xml
This adds working dependencies back to `bitbots_bringup`.
Closes #151
> Bringup depend on working packages

- bitbots_bringup/launch/motion.launch
Sets the speaker volume to 75% instead of 100%
bit-bots/humanoid_league_misc/pull/130
> Fix: Set speaker value to 75% instead of 100%

- bitbots_utils/package.xml
Add missing `demo_nodes_cpp` dependency
> Add missing `demo_nodes_cpp` dependency

- bitbots_bringup/package.xml
- Make dependency on `wolfgang_webots_sim` conditional (if we are on a robot)
bitbots_meta/pull/187
bitbots_meta/pull/189
bit-bots/bitbots_tools/pull/143
> Fix: Conditional dependency on wolfgang_webots_sim

- bitbots_extrinsic_calibration/CMakeLists.txt
- bitbots_extrinsic_calibration/include/extrinsic_calibration/extrinsic_calibration.h
- bitbots_extrinsic_calibration/package.xml
- bitbots_extrinsic_calibration/src/extrinsic_calibration.cpp
- Use rclcpp binaries for the events executor
PR because https://github.com/ros2/rclcpp/pull/2155 is merged and released.
> Use rclcpp events executor

- bitbots_utils/bitbots_utils/game_settings.py
- bitbots_utils/config/game_settings.yaml
- bitbots_utils/config/game_settings_options.yaml
- bitbots_utils/scripts/game_settings.py
The `game_settings.yaml` was adapted to include a `monitoring_host_ip`, so that it can be dynamically configured in other nodes (namely the udp_brige https://github.com/bit-bots/udp_bridge/pull/22).
This was done, because we have to potentially change the `monitoring_host_ip` for every game (for different competition/field ip range/laptop configurations), so it makes sense to include it in the game_settings script, which is used by the `robot_compile.py` script.
To allow for validation of both `game_settings.yaml` values with predefined options, as well as just by a predefined type, like `IPv4Address` in this case the script was also adapted.
> Game settings add monitoring host

- bitbots_bringup/launch/highlevel.launch
- bitbots_bringup/launch/vision.launch
Fix launch hierarchy since highlevel included vision_standalone launch, which now includes the base launch. That would include base launch twice.
#226
> Fix highlevel launch with new vision launch

- bitbots_utils/launch/rosbag_record.launch.py
Removes the topic throttle nodes.
Because of the additional subscription, those subscribed topics are slowed down (by 30%).
This also removes the recording of the `/line_mask_relative_pc_to_record` topic as it is more complex to republish the point cloud from CPP and this could be reconstructed from the logged images.
https://github.com/bit-bots/bitbots_vision/pull/343
> Fix: Rosbag record remove throttle nodes for performance reasons

- bitbots_bringup/launch/teamplayer.launch
Reverts bit-bots/bitbots_misc#234
As the competition is over, running the tools by default is no longer needed.
> Revert "Teamplayer: activate tools"

- bitbots_utils/config/game_settings_options.yaml
The `position_number` game setting is expected to be of type `int` but it was set to `str`.
> Fix position_number type to int
